version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo Entered the install phase...
      - npm install --global yarn
      - yarn install

  pre_build:
    commands:
      - echo ENV Values
      - echo ---------------------------------
      - echo $AWS_DEFAULT_REGION
      - echo $AWS_ACCOUNT_ID
      - echo $CDN_DISTRIBUTION_ID
      - echo ---------------------------------

  build:
    commands:
      - echo Entered the build phase...
      - yarn build

  post_build:
    commands:
      # - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - aws cloudfront create-invalidation --distribution-id $CDN_DISTRIBUTION_ID --paths "/*"

artifacts:
  files:
    - build/**/*
